pagy:
  product:
    per_page: 9
  bill:
    per_page: 5
  user:
    per_page: 8
cart:
  size:
    default: 0
    min: 1
  increment:
    condition: "true"
    default: 1
  decrement:
    default: -1
bill:
  amount:
    min: 0
  payment_method:
    max_length: 255
  status:
    completed: 1
product_detail:
  price_0: 0
  price_20: 20
  price_50: 50
  price_100: 100
  price_max: 1000000
search_type:
  name: "name"
  category: "category"
  brand: "brand"
product:
  product_top: 8
account:
  role:
    title: "role"
  status:
    title: "status"
